parameters:
    vladyslav_lysenko_simple_test_form.example.class: VladyslavLysenko\SimpleTestFormBundle\Services\TestParser

services:
    vladyslav_lysenko_simple_test_form.example:
        class: %vladyslav_lysenko_simple_test_form.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
