parameters:
#    vladyslav_lysenko_user.example.class: VladyslavLysenko\UserBundle\Example

services:
#    vladyslav_lysenko_user.example:
#        class: %vladyslav_lysenko_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
