security:
    encoders:
        VladyslavLysenko\UserBundle\Entity\User:
                            algorithm: sha512
                            encode-as-base64: true
                            iterations: 10

    role_hierarchy:
        ROLE_USER: IS_AUTHENTICATED_ANONYMOUSLY
        ROLE_ADMIN:       ROLE_USER
#        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            entity: { class: VladyslavLysenkoUserBundle:User, property: email }

    firewalls:
        main:
            pattern: /.*
            form_login:
               check_path: /login_check
               login_path: /login
               default_target_path: admin_index
               csrf_provider: form.csrf_provider
            logout:
               path:   /logout
               target: /
            security: true
            anonymous: true
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/demo/secured/login$
            security: false

        secured_area:
            pattern:    ^/demo/secured/
            form_login:
                check_path: _security_check
                login_path: _demo_login
            logout:
                path:   _demo_logout
                target: _demo
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
                - { path: /admin, role: ROLE_USER }
                - { path: /.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
